# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Sacchari.de'
description: 'Website über Kohlenhydrate'
permalink: pretty
logo: "/assets/logos/logo.svg"

# Pagination
paginate: 5
paginate_path: blog/page:num

favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# Header nav
navigation_header:
- title: Startseite
  url: /
- title: Monosaccharide
  url: /monosaccharide/
- title: Disaccharide
  url: /disaccharide/
- title: Polysaccharide
  url: /polysaccharide/

# Footer nav
navigation_footer:
- title: Erstellt von Bastian Küpker

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text: ""
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
